-- Longest Running Queries
SELECT
  DATE_TRUNC('hour', START_TIME) AS HOUR_WINDOW,
  AVG(EXECUTION_TIME) AS AVG_EXECUTION_TIME_MS
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
GROUP BY 1
ORDER BY 1;
